type Lang = 'en' | 'oj' | 'cr' | 'iu' | 'fr' | 'mi';

const TERRITORY_STORAGE_KEY = 'territory-settings';

const getStoredTerritoryAck = (): string | null => {
  try {
    const saved = localStorage.getItem(TERRITORY_STORAGE_KEY);
    if (saved) {
      const settings = JSON.parse(saved);
      if (settings.useCustom && settings.customAcknowledgment) {
        return settings.customAcknowledgment;
      }
      if (settings.primaryTerritory) {
        return null; // Will be generated by the component
      }
    }
  } catch {
    // Ignore
  }
  return null;
};

const STRINGS: Record<Lang, Record<string, string>> = {
  en: {
    greeting: 'Welcome',
    territory_ack: 'We acknowledge that we work on the traditional territories of Indigenous peoples across Turtle Island.'
  },
  oj: {
    greeting: 'Boozhoo',
    territory_ack: 'We acknowledge that we work on the traditional territories of Indigenous peoples across Turtle Island.'
  },
  cr: { greeting: 'Tansi', territory_ack: 'We acknowledge that we work on the traditional territories of Indigenous peoples across Turtle Island.' },
  iu: { greeting: 'ᐊᓘ', territory_ack: 'We acknowledge that we work on the traditional territories of Indigenous peoples across Turtle Island.' },
  fr: { greeting: 'Bienvenue', territory_ack: 'Nous reconnaissons que nous travaillons sur les territoires traditionnels des peuples autochtones.' },
  mi: { greeting: 'Kwe', territory_ack: 'We acknowledge that we work on the traditional territories of Indigenous peoples across Turtle Island.' }
};

export const getString = (lang: Lang | string, key: string) => {
  const l = (lang as Lang) || 'en';
  
  // For territory acknowledgment, check stored custom settings first
  if (key === 'territory_ack') {
    const custom = getStoredTerritoryAck();
    if (custom) return custom;
  }
  
  return (STRINGS[l] && STRINGS[l][key]) || STRINGS['en'][key] || '';
};
